@BASE_URL = http://localhost/api


### VEHICLE ROUTES ###

POST {{BASE_URL}}/vehicle
User-Agent: rest-client
Content-Type: application/json
x-api-key: ef0dbe9cb1591983b808fc3cfc3f563069d4731a9c6963370f88026a2ef36758

{
  "vin": "TMBZZZAAZGD640889"
}

###

GET {{BASE_URL}}/vehicles
x-api-key: ef0dbe9cb1591983b808fc3cfc3f563069d4731a9c6963370f88026a2ef36758

###


PATCH {{BASE_URL}}/vehicle/TMBZZZAAZGD640887
Content-Type: application/json
x-api-key: ef0dbe9cb1591983b808fc3cfc3f563069d4731a9c6963370f88026a2ef36758

{
  "model": "Octav22a"
}


###
GET {{BASE_URL}}/vehicle/TMBZZZAAZGD640887
Content-Type: application/json
x-api-key: ef0dbe9cb1591983b808fc3cfc3f563069d4731a9c6963370f88026a2ef36758


###



### TRIP ROUTES ###

GET {{BASE_URL}}/trips
x-api-key: ef0dbe9cb1591983b808fc3cfc3f563069d4731a9c6963370f88026a2ef36758
Content-Type: application/json

###

DELETE {{BASE_URL}}/trips
x-api-key: ef0dbe9cb1591983b808fc3cfc3f563069d4731a9c6963370f88026a2ef36758
Content-Type: application/json

###


DELETE {{BASE_URL}}/trip/128
Content-Type: application/json
x-api-key: ef0dbe9cb1591983b808fc3cfc3f563069d4731a9c6963370f88026a2ef36758

###


POST {{BASE_URL}}/trip
Content-Type: application/json
x-api-key: 198b1403fd6a8fd7ddc2d7cd5601fc5f44d68d63d6bd0af72492c683cf35b0aa

{
  "startTimestamp": "2025-03-07T15:03:23.234Z",
  "endTimestamp": "2025-03-07T15:03:23.234Z",
  "startLocation": null,
  "endLocation": null,
  "startMileage": "11707",
  "endMileage": "11708",
  "tripCategory": "business",
  "vehicle": {"vin": "TMBZZZAAZGD640887" },
  "recorded": true,
  "tripStatus": "completed",
  "detourNote": "",
  "checked": false
}

### USER ROUTES ### 


GET {{BASE_URL}}/users
Content-Type: application/json
x-api-key: ef0dbe9cb1591983b808fc3cfc3f563069d4731a9c6963370f88026a2ef36758


###
POST {{BASE_URL}}/user

x-api-key: "ef0dbe9cb1591983b808fc3cfc3f563069d4731a9c6963370f88026a2ef36758"
Content-Type: "application/json"
{
  "username": "dispatcher",
  "password": "password",
  "firstName": "Max",
  "lastName": "Mustermann",
   "email": "max@gmail.com",
   "role": "dispatcher"
}

### Admin User

POST {{BASE_URL}}/user
Content-Type: application/json
x-api-key: ef0dbe9cb1591983b808fc3cfc3f563069d4731a9c6963370f88026a2ef36758

{
  "username": "admin",
  "password": "einpasswort",
  "firstName": "Gustav",
  "lastName": "Müller",
  "email": "Gustav.Müller@novacorp.com",
  "role": "admin"
}

###


